[package]
name = "dir2draft_rust"
version = "0.1.1"
# about = "Converts a subdirectory of MD files into a 1 MD file"
edition = "2024"

[dependencies]
clap = {version = "4.5.38" , features = ["derive"] }
itertools = "0.14.0"
walkdir = "2.5.0"
